# Generated by Django 2.2.3 on 2019-09-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0021_user_sso_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='limits_private_thread_invites_to',
            field=models.PositiveIntegerField(choices=[(0, 'Everybody'), (1, 'Users I follow'), (2, 'Nobody')], default=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribe_to_replied_threads',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Notify'), (2, 'Notify with e-mail')], default=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribe_to_started_threads',
            field=models.PositiveIntegerField(choices=[(0, 'No'), (1, 'Notify'), (2, 'Notify with e-mail')], default=2),
        ),
    ]
