# Generated by Django 2.2.3 on 2019-09-29 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0022_deleteduser'),
        ('misago_users', '0022_auto_20190926_2200'),
    ]

    operations = [
    ]
