# Generated by Django 2.2.3 on 2019-10-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0023_merge_20190929_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(default='', max_length=30),
        ),
    ]
