# Generated by Django 2.2.3 on 2019-10-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0024_auto_20191002_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registry_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
