# Generated by Django 2.2.3 on 2019-10-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0025_user_registry_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registry_number',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
