# Generated by Django 2.2.3 on 2019-10-13 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misago_users', '0027_auto_20191011_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='real_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='region',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registry_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialization',
        ),
    ]
